### ISSUE TITLE
Indices file

### ISSUE THREAD

**Issue by Mohamad73** [inubushi/LSTM-KTH#1]
Hi, 
I am trying to run this code on windows 7 python 3.  I am running the prepare code and getting " No such file or directory: 'KTH_sequences.txt'". Where am I supposed to get this file from?
Thank you

**Comment by inubushi** [comment]
Hi,

Sorry for the delay. I will check the repo and add this file soon.

**Comment by inubushi** [comment]
From what I remember, this is where I put the locations and classes for the KTH sequences. Please give me a day or two.

**Comment by inubushi** [comment]
This file is included in the KTH dataset as 00sequences.txt. I will include it in the repo shortly.

**Comment by inubushi** [comment]
Done.
